### PR TITLE
[ID-78] User survey responses not accessible

### LINKED ISSUE #78: [BUG] User survey responses not accessible
Right after successful submission of completed survey loading user survey responses succeeds but returns "null" 

```
POST https://api.rokwire.illinois.edu/surveys/api/survey-responses => 200
{
  "id":"d810a39b-7796-4705-9b1e-64067935a1ba",
  "data":{...},
  "type":"admin",
  "scored":true,
  "title":"Skills Self-Evaluation",
  "more_info":"",
  "default_data_key":"how_well",
  "default_data_key_rule":null,
  "result_rules":"...",
  "result_json":"...",
  "response_keys":null,
  "constants":{
    "low_score":0.33,
    "medium_score":0.66
  },
  "strings":{...},
  "sub_rules":{
    
  },
  "date_created":"2022-12-19T23:10:26.513Z",
  "date_updated":"2024-09-09T14:45:32.403Z",
  "stats":{...},
  "calendar_event_id":""
}
```

Then
```
GET https://api.rokwire.illinois.edu/surveys/api/survey-responses?survey_types=bessi&limit=10 => 200
null
```

Source: https://github.com/rokwire/illinois-app/issues/4330

### PR DESCRIPTION
**Pull request by stefanvit**
## Description
 User survey responses not accessible

**Resolves #78 

## Review Time Estimate
- [ ] Immediately
- [ ] Within a week
- [x] When possible

## Type of changes
- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Other (any another change that does not fall in one of the above categories.)

## Checklist:
- [x] I have signed the Rokwire Contributor License Agreement ([CLA](https://rokwire.org/rokwire_cla)). (_Any contributor who is not an employee of the University of Illinois whose official duties include contributing to the Rokwire software, or who is not paid by the Rokwire project, needs to sign the CLA before their contribution can be accepted._)
- [x] I have updated the [CHANGELOG](../CHANGELOG.md).
- [x] I have read the [Contributor Guidelines](../CONTRIBUTING.md).
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My change requires updating the documentation.
- [ ] I have made necessary changes to the documentation.
- [ ] I have added tests related to my changes.
- [x] My changes generate no new warnings.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by stefanvit** [comment]
Hi @shurwit I've made the fixes and think it works fine now. if you could take a quick look so i could merge it and deploy a new version on dev and resolve the problem. Thank you for your time.

**Comment by shurwit** [comment]
Hi @stefanvit, thanks for working on this! Could you please still set the `type` to be "user" as a default value if the API request left this field empty?

**Comment by stefanvit** [comment]
Hi @shurwit ok i will in the morning, but doesn't the problem here https://github.com/rokwire/surveys-building-block/issues/78 stays if i do? Thank you again for your time.

**Comment by shurwit** [comment]
Hi @stefanvit , I made this change myself in this commit [here](https://github.com/rokwire/surveys-building-block/pull/83/commits/1d445c4a93740bc6e92302825af4973076dcb9a3) to make sure that it was clear what I meant. Essentially it is only applied as a default now if the caller does not specify the value. That way the caller may choose to set the value, but if not we don't end up with an empty string in the type field.

**Pull request merged**
